"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[3030],{917:function(j,c,l){l.r(c);var d=l(279),a=l.n(d),t=l(3519),h=l(3236),s=l(2086);function D(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,h.useEffect)(function(){var e;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(p.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(e=document.getElementById("active-nav-item"))===null||e===void 0||e.scrollIntoView({behavior:"smooth",block:"center"})},[]);var x=n.components||{},o=x.wrapper;return o?(0,s.jsx)(o,a()(a()({},n),{},{children:(0,s.jsx)(i,{})})):i();function i(){var e=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",h3:"h3",div:"div",pre:"pre",code:"code",h4:"h4",ul:"ul",li:"li"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(e.h1,{id:"\u4F7F\u7528-vue",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u4F7F\u7528-vue",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u4F7F\u7528 Vue"]}),`
`,(0,s.jsx)(e.p,{children:"\u672C\u6587\u4ECB\u7ECD\u5982\u4F55\u5728 Umi \u4F7F\u7528 Vue , Umi Vue \u5927\u90E8\u5206\u914D\u7F6E\u548C React \u76F8\u540C\uFF0C\u8FD9\u91CC\u53EA\u5217\u51FA\u4E00\u4E9B Vue \u72EC\u6709\u7684\u914D\u7F6E"}),`
`,(0,s.jsxs)(e.h2,{id:"\u542F\u52A8\u65B9\u5F0F",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u542F\u52A8\u65B9\u5F0F",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u542F\u52A8\u65B9\u5F0F"]}),`
`,(0,s.jsxs)(e.h3,{id:"\u5B89\u88C5",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B89\u88C5",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u5B89\u88C5"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(e.code,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"pnpm add  @umijs/preset-vue -D"})})})})}),`
`,(0,s.jsxs)(e.h3,{id:"\u914D\u7F6E\u9884\u8BBE",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u9884\u8BBE",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u9884\u8BBE"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"# ."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"umirc"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ts"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"or"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"/"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ts"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"\u4E2D"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"presets:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"require"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"resolve"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'@umijs/preset-vue'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:")],"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "})]})})}),`
`,(0,s.jsxs)(e.h2,{id:"\u8DEF\u7531",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u8DEF\u7531"]}),`
`,(0,s.jsxs)(e.h3,{id:"\u914D\u7F6E\u5F0F\u8DEF\u7531",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u5F0F\u8DEF\u7531",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u5F0F\u8DEF\u7531"]}),`
`,(0,s.jsx)(t.v0,{children:(0,s.jsx)(e.p,{children:"\u8FD9\u91CC\u4EC5\u5217\u51FA\u548C React \u8DEF\u7531\u914D\u7F6E\u5DEE\u5F02\u90E8\u5206"})}),`
`,(0,s.jsxs)(e.h4,{id:"name",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#name",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"name"]}),`
`,(0,s.jsx)(e.p,{children:"\u547D\u540D\u8DEF\u7531"}),`
`,(0,s.jsxs)(e.p,{children:["\u9664\u4E86 ",(0,s.jsx)(e.code,{children:"path"})," \u4E4B\u5916\uFF0C\u4F60\u8FD8\u53EF\u4EE5\u4E3A\u4EFB\u4F55\u8DEF\u7531\u63D0\u4F9B ",(0,s.jsx)(e.code,{children:"name"})]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/user/:username'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'user'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'index'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u8981\u94FE\u63A5\u5230\u4E00\u4E2A\u547D\u540D\u7684\u8DEF\u7531\uFF0C\u53EF\u4EE5\u5411 ",(0,s.jsx)(e.code,{children:"router-link"})," \u7EC4\u4EF6\u7684 to \u5C5E\u6027\u4F20\u9012\u4E00\u4E2A\u5BF9\u8C61\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"html","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"html","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"router-link"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:":to"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:`"{ name: 'user', params: { username: 'erina' }}"`}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  User"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"router-link"}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:">"})]})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u6548\u679C\u548C\u547D\u4EE4\u5F0F\u5730\u8C03\u7528 ",(0,s.jsx)(e.code,{children:"router.push"})," \u4E00\u81F4\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsx)(e.code,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"push"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'user'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"params:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"username:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'erina'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } })"})]})})})}),`
`,(0,s.jsxs)(e.p,{children:["\u5728\u8FD9\u65B9\u6CD5\u90FD\u80FD\u5BFC\u822A\u5230\u8DEF\u5F84 ",(0,s.jsx)(e.code,{children:"/user/erina"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h4,{id:"redirect",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#redirect",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"redirect"]}),`
`,(0,s.jsxs)(e.p,{children:["\u91CD\u5B9A\u5411\u4E5F\u662F\u901A\u8FC7 ",(0,s.jsx)(e.code,{children:"routes"})," \u914D\u7F6E\u6765\u5B8C\u6210\uFF0C\u4E0B\u9762\u4F8B\u5B50\u662F\u4ECE ",(0,s.jsx)(e.code,{children:"/home"})," \u91CD\u5B9A\u5411\u5230 ",(0,s.jsx)(e.code,{children:"/"}),"\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/home'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"redirect:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u91CD\u5B9A\u5411\u7684\u76EE\u6807\u4E5F\u53EF\u4EE5\u662F\u4E00\u4E2A\u547D\u540D\u7684\u8DEF\u7531\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/home'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"redirect:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'homepage'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h4,{id:"alias",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#alias",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"alias"]}),`
`,(0,s.jsxs)(e.p,{children:["\u91CD\u5B9A\u5411\u662F\u6307\u5F53\u7528\u6237\u8BBF\u95EE ",(0,s.jsx)(e.code,{children:"/home"})," \u65F6\uFF0CURL \u4F1A\u88AB ",(0,s.jsx)(e.code,{children:"/"})," \u66FF\u6362\uFF0C\u7136\u540E\u5339\u914D\u6210 ",(0,s.jsx)(e.code,{children:"/"}),"\u3002\u90A3\u4E48\u4EC0\u4E48\u662F\u522B\u540D\u5462\uFF1F"]}),`
`,(0,s.jsxs)(e.p,{children:["\u5C06 ",(0,s.jsx)(e.code,{children:"/"})," \u522B\u540D\u4E3A ",(0,s.jsx)(e.code,{children:"/home"}),"\uFF0C\u610F\u5473\u7740\u5F53\u7528\u6237\u8BBF\u95EE ",(0,s.jsx)(e.code,{children:"/home"})," \u65F6\uFF0CURL \u4ECD\u7136\u662F ",(0,s.jsx)(e.code,{children:"/home"}),"\uFF0C\u4F46\u4F1A\u88AB\u5339\u914D\u4E3A\u7528\u6237\u6B63\u5728\u8BBF\u95EE ",(0,s.jsx)(e.code,{children:"/"}),"\u3002"]}),`
`,(0,s.jsx)(e.p,{children:"\u4E0A\u9762\u5BF9\u5E94\u7684\u8DEF\u7531\u914D\u7F6E\u4E3A\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'index'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"alias:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/home'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u901A\u8FC7\u522B\u540D\uFF0C\u4F60\u53EF\u4EE5\u81EA\u7531\u5730\u5C06 UI \u7ED3\u6784\u6620\u5C04\u5230\u4E00\u4E2A\u4EFB\u610F\u7684 URL\uFF0C\u800C\u4E0D\u53D7\u914D\u7F6E\u7684\u5D4C\u5957\u7ED3\u6784\u7684\u9650\u5236\u3002\u4F7F\u522B\u540D\u4EE5 ",(0,s.jsx)(e.code,{children:"/"})," \u5F00\u5934\uFF0C\u4EE5\u4F7F\u5D4C\u5957\u8DEF\u5F84\u4E2D\u7684\u8DEF\u5F84\u6210\u4E3A\u7EDD\u5BF9\u8DEF\u5F84\u3002\u4F60\u751A\u81F3\u53EF\u4EE5\u5C06\u4E24\u8005\u7ED3\u5408\u8D77\u6765\uFF0C\u7528\u4E00\u4E2A\u6570\u7EC4\u63D0\u4F9B\u591A\u4E2A\u522B\u540D\uFF1A"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/users'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'users'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u4E3A\u8FD9 3 \u4E2A URL \u5448\u73B0 UserList"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// - /users"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// - /users/list"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// - /people"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"        { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"''"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/users/UserList'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"alias:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/people'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'list'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"] },"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h3,{id:"\u9875\u9762\u8DF3\u8F6C",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u9875\u9762\u8DF3\u8F6C",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u9875\u9762\u8DF3\u8F6C"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"html","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"html","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"script"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"lang"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:'"ts"'}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"setup"}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"useRouter"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"useRoute"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"useRouter"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"route"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"useRoute"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"onHello"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"push"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'search'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"query:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      ..."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"route"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"query"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  })"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"script"}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:">"})]})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u66F4\u591A",(0,s.jsx)(e.a,{href:"https://router.vuejs.org/guide/advanced/composition-api.html#accessing-the-router-and-current-route-inside-setup",children:"\u8BE6\u89C1"})]}),`
`,(0,s.jsxs)(e.h3,{id:"router-link",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#router-link",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"router-link"]}),`
`,(0,s.jsx)(e.p,{children:(0,s.jsx)(e.a,{href:"https://router.vuejs.org/guide/#router-link",children:"\u8BE6\u89C1"})}),`
`,(0,s.jsxs)(e.h3,{id:"router-view",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#router-view",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"router-view"]}),`
`,(0,s.jsx)(e.p,{children:(0,s.jsx)(e.a,{href:"https://router.vuejs.org/guide/#router-view",children:"\u8BE6\u89C1"})}),`
`,(0,s.jsxs)(e.h2,{id:"\u8FD0\u884C\u65F6\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsxs)(e.p,{children:["\u53EF\u4EE5\u901A\u8FC7\u5728\u7EA6\u5B9A\u7684 ",(0,s.jsx)(e.code,{children:"src/app.tsx"})," \u901A\u8FC7 export \u914D\u7F6E\u6765\u63A7\u5236 vue vue-router \u76F8\u5173\u7684\u914D\u7F6E"]}),`
`,(0,s.jsxs)(e.h3,{id:"router",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#router",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"router"]}),`
`,(0,s.jsx)(e.p,{children:"\u914D\u7F6E\u8DEF\u7531\u914D\u7F6E"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// src/app.tsx"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"RouterConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// @ts-ignore"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"scrollBehavior"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'scrollBehavior'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.h3,{id:"onmountedapp-router",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#onmountedapp-router",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"onMounted({app, router})"]}),`
`,(0,s.jsx)(e.p,{children:"Vue app mount \u6210\u529F\u56DE\u8C03, \u8FD9\u91CC\u53EF\u4EE5\u62FF\u5230 app \u7684\u5B9E\u4F8B\u53CA router \u7684\u5B9E\u4F8B, \u53EF\u4EE5\u8FDB\u884C\u5168\u5C40\u7EC4\u4EF6\u6CE8\u518C, \u8DEF\u7531\u62E6\u622A\u5668\u7B49\u3002"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"onMounted"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"app"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }: "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"any"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'onMounted'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"app"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"router"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"app"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"provide"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi-hello'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"h:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'hello'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"w:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'word'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h3,{id:"rootcontainercontainer",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#rootcontainercontainer",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"rootContainer(container)"]}),`
`,(0,s.jsx)(e.p,{children:"\u4FEE\u6539\u4EA4\u7ED9 vue-router \u6E32\u67D3\u65F6\u7684\u6839\u7EC4\u4EF6\u3002"}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\u7528\u4E8E\u5728\u5916\u9762\u5305\u4E00\u4E2A\u7236\u7EC4\u4EF6"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"h"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'vue'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"rootContainer"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"container"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"h"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ThemeProvider"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"null"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"container"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h2,{id:"examples",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#examples",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"examples"]}),`
`,(0,s.jsx)(e.p,{children:"\u66F4\u591A\u8BE6\u89C1 demo"}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsx)(e.li,{children:(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi/tree/master/examples/boilerplate-vue",children:"boilerplate-vue"})}),`
`,(0,s.jsx)(e.li,{children:(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi/tree/master/examples/with-vue-pinia",children:"with-vue-pinia"})}),`
`,(0,s.jsx)(e.li,{children:(0,s.jsx)(e.a,{href:"https://github.com/umijs/umi/tree/master/examples/with-vue-element-plus",children:"with-vue-element-plus"})}),`
`]})]})}}c.default=D}}]);
