"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[3137],{4672:function(j,c,l){l.r(c);var d=l(279),a=l.n(d),t=l(3236),s=l(2086);function D(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var e;if(window.location.hash.length!==0){var x=decodeURIComponent(window.location.hash);setTimeout(function(){var r;(r=document.getElementById(x.slice(1)))===null||r===void 0||r.scrollIntoView()},100)}else window.scrollTo(0,0);(e=document.getElementById("active-nav-item"))===null||e===void 0||e.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},o=h.wrapper;return o?(0,s.jsx)(o,a()(a()({},n),{},{children:(0,s.jsx)(i,{})})):i();function i(){var e=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",code:"code",div:"div",pre:"pre",blockquote:"blockquote",h3:"h3",h4:"h4",ul:"ul",li:"li",ol:"ol"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(e.h1,{id:"\u8FD0\u884C\u65F6\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8FD0\u884C\u65F6\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u8FD0\u884C\u65F6\u914D\u7F6E"]}),`
`,(0,s.jsx)(e.p,{children:"\u8FD0\u884C\u65F6\u914D\u7F6E\u548C\u914D\u7F6E\u7684\u533A\u522B\u662F\u4ED6\u8DD1\u5728\u6D4F\u89C8\u5668\u7AEF\uFF0C\u57FA\u4E8E\u6B64\uFF0C\u6211\u4EEC\u53EF\u4EE5\u5728\u8FD9\u91CC\u5199\u51FD\u6570\u3001tsx\u3001import \u6D4F\u89C8\u5668\u7AEF\u4F9D\u8D56\u7B49\u7B49\uFF0C\u6CE8\u610F\u4E0D\u8981\u5F15\u5165 node \u4F9D\u8D56\u3002"}),`
`,(0,s.jsxs)(e.h2,{id:"\u914D\u7F6E\u65B9\u5F0F",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u65B9\u5F0F",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u65B9\u5F0F"]}),`
`,(0,s.jsxs)(e.p,{children:["\u7EA6\u5B9A ",(0,s.jsx)(e.code,{children:"src/app.tsx"})," \u4E3A\u8FD0\u884C\u65F6\u914D\u7F6E\u3002"]}),`
`,(0,s.jsxs)(e.h2,{id:"typescript-\u63D0\u793A",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#typescript-\u63D0\u793A",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"TypeScript \u63D0\u793A"]}),`
`,(0,s.jsx)(e.p,{children:"\u5982\u679C\u4F60\u60F3\u5728\u5199\u914D\u7F6E\u65F6\u4E5F\u6709\u63D0\u793A\uFF0C\u53EF\u4EE5\u901A\u8FC7 umi \u7684 defineApp \u65B9\u6CD5\u5B9A\u4E49\u914D\u7F6E\u3002"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"defineApp"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"defineApp"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"layout"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:'"umi"'}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    };"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"})"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// or "})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"RuntimeConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"layout"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"RuntimeConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"["}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'layout'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"] = () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"title:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h2,{id:"\u914D\u7F6E\u9879",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u9879",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u9879"]}),`
`,(0,s.jsxs)(e.blockquote,{children:[`
`,(0,s.jsx)(e.p,{children:"\u4EE5\u4E0B\u914D\u7F6E\u9879\u6309\u5B57\u6BCD\u6392\u5E8F\u3002"}),`
`]}),`
`,(0,s.jsxs)(e.h3,{id:"dva",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#dva",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"dva"]}),`
`,(0,s.jsxs)(e.p,{children:["\u5982\u679C\u4F60\u4F7F\u7528\u7684 dva\uFF0C\u90A3\u4E48\u652F\u6301\u914D\u7F6E dva \u63D2\u4EF6\u7684\u8FD0\u884C\u65F6\u914D\u7F6E\uFF0C\u5177\u4F53\u53C2\u8003",(0,s.jsx)(e.a,{href:"../max/dva",children:"\u63D2\u4EF6\u914D\u7F6E"}),"\u3002"]}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"immer:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"extraModels:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" [],"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.h4,{id:"extramodels",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#extramodels",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"extraModels"]}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsx)(e.li,{children:"Type: string[]"}),`
`,(0,s.jsx)(e.li,{children:"Default: [] \u914D\u7F6E\u989D\u5916\u5230 dva model\u3002"}),`
`]}),`
`,(0,s.jsxs)(e.h4,{id:"immer",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#immer",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"immer"]}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsx)(e.li,{children:"Type: boolean | object"}),`
`,(0,s.jsx)(e.li,{children:"Default: false \u8868\u793A\u662F\u5426\u542F\u7528 immer \u4EE5\u65B9\u4FBF\u4FEE\u6539 reducer\u3002"}),`
`]}),`
`,(0,s.jsxs)(e.p,{children:["\u6CE8\uFF1A\u5982\u9700\u517C\u5BB9 IE11\uFF0C\u9700\u914D\u7F6E ",(0,s.jsx)(e.code,{children:"{ immer: { enableES5: true }}"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"\u6570\u636E\u6D41",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6570\u636E\u6D41",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u6570\u636E\u6D41"]}),`
`,(0,s.jsxs)(e.p,{children:["\u82E5\u4F60\u9700\u8981\u5B9A\u4E49\u521D\u59CB\u5316\u6570\u636E\uFF0C\u4F7F\u7528 ",(0,s.jsx)(e.code,{children:"getInitialState"})," \u3001",(0,s.jsx)(e.code,{children:"useModel"})," \u7B49 ",(0,s.jsx)(e.a,{href:"../max/data-flow",children:"\u6570\u636E\u6D41"})," \u76F8\u5173\u529F\u80FD\uFF1A"]}),`
`,(0,s.jsxs)(e.ol,{children:[`
`,(0,s.jsxs)(e.li,{children:[`
`,(0,s.jsxs)(e.p,{children:["\u4F60\u53EF\u4EE5\u521B\u5EFA\u81EA\u5E26\u6570\u636E\u6D41\u529F\u80FD\u7684 ",(0,s.jsx)(e.code,{children:"@umijs/max"})," \u9879\u76EE\uFF0C\u8BE6\u89C1 ",(0,s.jsx)(e.a,{href:"../max/introduce",children:"Umi max \u7B80\u4ECB"})," \u3002"]}),`
`]}),`
`,(0,s.jsxs)(e.li,{children:[`
`,(0,s.jsx)(e.p,{children:"\u6216\u8005\u624B\u52A8\u5F00\u542F\u6570\u636E\u6D41\u529F\u80FD\u7684\u63D2\u4EF6\u4F7F\u7528\u8BE5\u529F\u80FD\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(e.code,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  pnpm add -D @umijs/plugins"})})})})}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// .umirc.ts"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"plugins:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'@umijs/plugins/dist/initial-state'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'@umijs/plugins/dist/model'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  ],"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"initialState:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"model:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`]}),`
`]}),`
`,(0,s.jsxs)(e.h3,{id:"layout",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#layout",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"layout"]}),`
`,(0,s.jsxs)(e.p,{children:["\u4FEE\u6539",(0,s.jsx)(e.a,{href:"../max/layout-menu",children:"\u5185\u7F6E\u5E03\u5C40"}),"\u7684\u914D\u7F6E\uFF0C\u6BD4\u5982\u914D\u7F6E\u9000\u51FA\u767B\u9646\u3001\u81EA\u5B9A\u4E49\u5BFC\u822A\u66B4\u9732\u7684\u6E32\u67D3\u533A\u57DF\u7B49\u3002"]}),`
`,(0,s.jsxs)(e.blockquote,{children:[`
`,(0,s.jsxs)(e.p,{children:["\u6CE8\u610F\uFF1A\u9700\u8981\u5F00\u542F ",(0,s.jsx)(e.a,{href:"../api/config#layout",children:"layout"})," \u63D2\u4EF6\uFF0C\u624D\u80FD\u4F7F\u7528\u5B83\u7684\u8FD0\u884C\u65F6\u914D\u7F6E\u3002"]}),`
`]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"layout"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"logout"}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {}, "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// do something"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u66F4\u591A\u5177\u4F53\u914D\u7F6E\u53C2\u8003",(0,s.jsx)(e.a,{href:"../max/layout-menu#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE",children:"\u63D2\u4EF6\u6587\u6863"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"onroutechange-routes-clientroutes-location-action-basename-",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#onroutechange-routes-clientroutes-location-action-basename-",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"onRouteChange({ routes, clientRoutes, location, action, basename })"]}),`
`,(0,s.jsx)(e.p,{children:"\u5728\u521D\u59CB\u52A0\u8F7D\u548C\u8DEF\u7531\u5207\u6362\u65F6\u505A\u4E00\u4E9B\u4E8B\u60C5\u3002"}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\u7528\u4E8E\u505A\u57CB\u70B9\u7EDF\u8BA1\uFF0C"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"onRouteChange"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"clientRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"action"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"basename"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"bacon"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\u7528\u4E8E\u8BBE\u7F6E\u6807\u9898\uFF0C"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"matchRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"onRouteChange"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"clientRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"route"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"matchRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"clientRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"location"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"pathname"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:")?."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"pop"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"()?."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"route"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"route"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"document"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"title"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"route"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"title"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" || "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"''"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h3,{id:"patchroutes-routes-",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#patchroutes-routes-",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"patchRoutes({ routes })"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"patchRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routeComponents"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"console"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"log"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'patchRoutes'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routeComponents"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsxs)(e.li,{children:[`
`,(0,s.jsxs)(e.p,{children:[(0,s.jsx)(e.code,{children:"routes"}),": \u6253\u5E73\u7684\u8DEF\u7531\u5217\u8868\u3002"]}),`
`]}),`
`,(0,s.jsxs)(e.li,{children:[`
`,(0,s.jsxs)(e.p,{children:[(0,s.jsx)(e.code,{children:"routeComponents"}),": \u8DEF\u7531\u5BF9\u5E94\u7684\u7EC4\u4EF6\u6620\u5C04\u3002"]}),`
`]}),`
`]}),`
`,(0,s.jsxs)(e.p,{children:["\u6CE8\uFF1A\u5982\u9700\u52A8\u6001\u66F4\u65B0\u8DEF\u7531\uFF0C\u5EFA\u8BAE\u4F7F\u7528 ",(0,s.jsx)(e.code,{children:"patchClientRoutes()"})," \uFF0C\u5426\u5219\u4F60\u53EF\u80FD\u9700\u8981\u540C\u65F6\u4FEE\u6539 ",(0,s.jsx)(e.code,{children:"routes"})," \u548C ",(0,s.jsx)(e.code,{children:"routeComponents"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"patchclientroutes-routes-",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#patchclientroutes-routes-",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"patchClientRoutes({ routes })"]}),`
`,(0,s.jsxs)(e.p,{children:["\u4FEE\u6539\u88AB react-router \u6E32\u67D3\u524D\u7684\u6811\u72B6\u8DEF\u7531\u8868\uFF0C\u63A5\u6536\u5185\u5BB9\u540C ",(0,s.jsx)(e.a,{href:"https://reactrouter.com/docs/en/v6/hooks/use-routes",children:"useRoutes"}),"\u3002"]}),`
`,(0,s.jsxs)(e.p,{children:["\u6BD4\u5982\u5728\u6700\u524D\u9762\u6DFB\u52A0\u4E00\u4E2A ",(0,s.jsx)(e.code,{children:"/foo"})," \u8DEF\u7531\uFF0C"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"tsx","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"tsx","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"Page"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'@/extraRoutes/foo'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"patchClientRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"unshift"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/foo'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"element:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(e.span,{style:{color:"#4EC9B0"},children:"Page"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.p,{children:["\u6BD4\u5982\u548C ",(0,s.jsx)(e.code,{children:"render"})," \u914D\u7F6E\u914D\u5408\u4F7F\u7528\uFF0C\u8BF7\u6C42\u670D\u52A1\u7AEF\u6839\u636E\u54CD\u5E94\u52A8\u6001\u66F4\u65B0\u8DEF\u7531\uFF0C"]}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"let"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"extraRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"patchClientRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" }) {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u6839\u636E extraRoutes \u5BF9 routes \u505A\u4E00\u4E9B\u4FEE\u6539"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"patch"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"extraRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"render"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"oldRender"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"fetch"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/api/routes'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    ."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"then"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"(("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"res"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"res"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"json"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"())"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    ."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"then"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"(("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"res"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"extraRoutes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"res"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"routes"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    });"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u6CE8\u610F\uFF1A"}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsx)(e.li,{children:"\u76F4\u63A5\u4FEE\u6539 routes\uFF0C\u4E0D\u9700\u8981\u8FD4\u56DE"}),`
`]}),`
`,(0,s.jsxs)(e.h3,{id:"qiankun",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#qiankun",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"qiankun"]}),`
`,(0,s.jsxs)(e.p,{children:["Umi \u5185\u7F6E\u4E86 ",(0,s.jsx)(e.code,{children:"qiankun"})," \u63D2\u4EF6\u6765\u63D0\u4F9B\u5FAE\u524D\u7AEF\u7684\u80FD\u529B\uFF0C\u5177\u4F53\u53C2\u8003",(0,s.jsx)(e.a,{href:"../max/micro-frontend",children:"\u63D2\u4EF6\u914D\u7F6E"}),"\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"renderoldrender-function",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#renderoldrender-function",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"render(oldRender: ",(0,s.jsx)(e.code,{children:"Function"}),")"]}),`
`,(0,s.jsx)(e.p,{children:"\u8986\u5199 render\u3002"}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\u7528\u4E8E\u6E32\u67D3\u4E4B\u524D\u505A\u6743\u9650\u6821\u9A8C\uFF0C"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"bash","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"render(oldRender)"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  fetch("}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/api/auth'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:").then(auth => {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" (auth.isLogin) { "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"() }"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"else"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      location.href = "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'/login'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"oldRender"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(e.h3,{id:"request",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#request",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"request"]}),`
`,(0,s.jsxs)(e.p,{children:["\u5982\u679C\u4F60\u4F7F\u7528\u4E86 ",(0,s.jsx)(e.code,{children:"import { request } from 'umi';"})," \u6765\u8BF7\u6C42\u6570\u636E\uFF0C\u90A3\u4E48\u4F60\u53EF\u4EE5\u901A\u8FC7\u8BE5\u914D\u7F6E\u6765\u81EA\u5B9A\u4E49\u4E2D\u95F4\u4EF6\u3001\u62E6\u622A\u5668\u3001\u9519\u8BEF\u5904\u7406\u9002\u914D\u7B49\u3002\u5177\u4F53\u53C2\u8003 ",(0,s.jsx)(e.a,{href:"../max/request",children:"request"})," \u63D2\u4EF6\u914D\u7F6E\u3002"]}),`
`,(0,s.jsxs)(e.h3,{id:"rootcontainerlastrootcontainer-args",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#rootcontainerlastrootcontainer-args",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"rootContainer(lastRootContainer, args)"]}),`
`,(0,s.jsx)(e.p,{children:"\u4FEE\u6539\u4EA4\u7ED9 react-dom \u6E32\u67D3\u65F6\u7684\u6839\u7EC4\u4EF6\u3002"}),`
`,(0,s.jsx)(e.p,{children:"\u6BD4\u5982\u7528\u4E8E\u5728\u5916\u9762\u5305\u4E00\u4E2A Provider\uFF0C"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"rootContainer"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"container"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"createElement"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"ThemeProvider"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"null"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"container"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"args \u5305\u542B\uFF1A"}),`
`,(0,s.jsxs)(e.ul,{children:[`
`,(0,s.jsx)(e.li,{children:"routes\uFF0C\u5168\u91CF\u8DEF\u7531\u914D\u7F6E"}),`
`,(0,s.jsx)(e.li,{children:"plugin\uFF0C\u8FD0\u884C\u65F6\u63D2\u4EF6\u673A\u5236"}),`
`,(0,s.jsx)(e.li,{children:"history\uFF0Chistory \u5B9E\u4F8B"}),`
`]}),`
`,(0,s.jsxs)(e.h2,{id:"\u66F4\u591A\u914D\u7F6E",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u66F4\u591A\u914D\u7F6E",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u66F4\u591A\u914D\u7F6E"]}),`
`,(0,s.jsx)(e.p,{children:"Umi \u5141\u8BB8\u63D2\u4EF6\u6CE8\u518C\u8FD0\u884C\u65F6\u914D\u7F6E\uFF0C\u5982\u679C\u4F60\u4F7F\u7528\u63D2\u4EF6\uFF0C\u80AF\u5B9A\u4F1A\u5728\u63D2\u4EF6\u91CC\u627E\u5230\u66F4\u591A\u8FD0\u884C\u65F6\u7684\u914D\u7F6E\u9879\u3002"})]})}}c.default=D}}]);
