"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[6685],{9214:function(p,r,e){e.r(r);var D=e(279),a=e.n(D),i=e(3519),h=e(3236),s=e(2086);function t(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,h.useEffect)(function(){var l;if(window.location.hash.length!==0){var x=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(x.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var j=n.components||{},d=j.wrapper;return d?(0,s.jsx)(d,a()(a()({},n),{},{children:(0,s.jsx)(o,{})})):o();function o(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",code:"code",h2:"h2",div:"div",pre:"pre",h3:"h3",h4:"h4",strong:"strong",table:"table",thead:"thead",tr:"tr",th:"th",tbody:"tbody",td:"td"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u72EC\u7ACB\u4F7F\u7528-mfsu",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u72EC\u7ACB\u4F7F\u7528-mfsu",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u72EC\u7ACB\u4F7F\u7528 MFSU"]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"MFSU"})," \u652F\u6301\u72EC\u7ACB\u5728\u975E umijs \u9879\u76EE\u4E2D\u4F7F\u7528\uFF0C\u672C\u6587\u5C06\u4F1A\u4ECB\u7ECD\u5982\u4F55\u5C06 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u63A5\u5165\u4F60\u7684 webpack \u9879\u76EE\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u793A\u4F8B\u9879\u76EE",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u793A\u4F8B\u9879\u76EE",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u793A\u4F8B\u9879\u76EE"]}),`
`,(0,s.jsx)(l.p,{children:"\u5982\u4F55\u63A5\u5165 MFSU \uFF1F\u63D0\u4F9B\u4EE5\u4E0B\u51E0\u4E2A \u793A\u4F8B\u9879\u76EE \u914D\u7F6E\u4F9B\u53C2\u8003\uFF1A"}),`
`,(0,s.jsxs)(l.p,{children:["Webpack \u914D\u7F6E\u793A\u4F8B\uFF1A",(0,s.jsx)("a",{href:"https://github.com/umijs/umi/tree/master/examples/mfsu-independent",target:"_blank",children:"examples/mfsu-independent"})]}),`
`,(0,s.jsxs)(l.p,{children:["CRA v5 \u914D\u7F6E\u793A\u4F8B\uFF1A",(0,s.jsx)("a",{href:"https://github.com/umijs/cra-v5-with-mfsu-example",target:"_blank",children:"cra-v5-with-mfsu-example"})]}),`
`,(0,s.jsxs)(l.h2,{id:"\u5B89\u88C5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5B89\u88C5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5B89\u88C5"]}),`
`,(0,s.jsxs)(l.p,{children:["\u9996\u5148\u5B89\u88C5 ",(0,s.jsx)(l.code,{children:"mfsu"})," \u7684\u4F9D\u8D56\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(l.code,{"data-language":"bash","data-theme":"default",children:(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  pnpm add -D @umijs/mfsu"})})})})}),`
`,(0,s.jsxs)(l.h2,{id:"\u914D\u7F6E-mfsu",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E-mfsu",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u914D\u7F6E MFSU"]}),`
`,(0,s.jsx)(l.p,{children:"\u914D\u7F6E MFSU \u4E00\u5171\u9700\u8981\u7B80\u5355\u7684\u56DB\u6B65\u64CD\u4F5C\uFF0C\u8BF7\u786E\u4FDD\u4EE5\u4E0B\u6240\u6709\u884C\u4E3A\u90FD\u53EA\u5728\u5F00\u53D1\u73AF\u5883\u751F\u6548\u3002"}),`
`,(0,s.jsxs)(l.h3,{id:"1-\u521D\u59CB\u5316\u5B9E\u4F8B",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#1-\u521D\u59CB\u5316\u5B9E\u4F8B",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"1. \u521D\u59CB\u5316\u5B9E\u4F8B"]}),`
`,(0,s.jsxs)(l.p,{children:["\u7B2C\u4E00\u6B65\uFF0C\u521D\u59CB\u5316\u4E00\u4E2A ",(0,s.jsx)(l.code,{children:"MFSU"})," \u5B9E\u4F8B\uFF0C\u8FD9\u662F ",(0,s.jsx)(l.code,{children:"MFSU"})," \u7684\u57FA\u7840\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"MFSU"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"require"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'@umijs/mfsu'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"webpack"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"require"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'webpack'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 1. init instance"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"new"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"MFSU"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"implementor:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"webpack"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"buildDepWithESBuild:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"2-\u6DFB\u52A0\u4E2D\u95F4\u4EF6",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#2-\u6DFB\u52A0\u4E2D\u95F4\u4EF6",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"2. \u6DFB\u52A0\u4E2D\u95F4\u4EF6"]}),`
`,(0,s.jsxs)(l.p,{children:["\u7B2C\u4E8C\u6B65\uFF0C\u6DFB\u52A0 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u7684 ",(0,s.jsx)(l.code,{children:"devServer"})," \u4E2D\u95F4\u4EF6\u5230 webpack-dev-server \u4E2D\uFF0C\u4ED6\u5C06\u4E3A\u4F60\u63D0\u4F9B ",(0,s.jsx)(l.code,{children:"MFSU"})," \u6240\u9700\u6253\u5305\u540E\u7684\u8D44\u6E90\uFF1A"]}),`
`,(0,s.jsxs)(l.h4,{id:"webpack-5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#webpack-5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"webpack 5"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"module"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"exports"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"devServer:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 2. add mfsu middleware"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setupMiddlewares"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"middlewares"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"devServer"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"middlewares"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"unshift"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        ..."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getMiddlewares"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      )"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"middlewares"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"webpack-4",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#webpack-4",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"webpack 4"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"module"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"exports"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"devServer:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 2. add mfsu middleware"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"onBeforeSetupMiddleware"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"devServer"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"for"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"middleware"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"of"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getMiddlewares"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()) {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"devServer"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"app"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"use"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"middleware"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"3-\u914D\u7F6E\u8F6C\u6362\u5668",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#3-\u914D\u7F6E\u8F6C\u6362\u5668",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"3. \u914D\u7F6E\u8F6C\u6362\u5668"]}),`
`,(0,s.jsxs)(l.p,{children:["\u7B2C\u4E09\u6B65\uFF0C\u4F60\u9700\u8981\u914D\u7F6E\u4E00\u79CD\u6E90\u7801\u8F6C\u6362\u5668\uFF0C\u4ED6\u7684\u4F5C\u7528\u662F\u7528\u6765\u6536\u96C6\u3001\u8F6C\u6362\u4F9D\u8D56\u5BFC\u5165\u8DEF\u5F84\uFF0C\u66FF\u6362\u4E3A ",(0,s.jsx)(l.code,{children:"MFSU"})," \u7684\u6A21\u5757\u8054\u90A6\u5730\u5740\uFF08\u4E2D\u95F4\u4EF6\u6240\u63D0\u4F9B\u7684\uFF09\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u6B64\u5904\u63D0\u4F9B\u4E24\u79CD\u65B9\u6848\uFF1A",(0,s.jsx)(l.code,{children:"babel plugins"})," \u6216 ",(0,s.jsx)(l.code,{children:"esbuild handler"})," \uFF0C\u4E00\u822C\u60C5\u51B5\u4E0B\u9009\u62E9 ",(0,s.jsx)(l.code,{children:"babel plugins"})," \u5373\u53EF\u3002"]}),`
`,(0,s.jsxs)(l.h4,{id:"babel-plugins",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#babel-plugins",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Babel Plugins"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5411 ",(0,s.jsx)(l.code,{children:"babel-loader"})," \u6DFB\u52A0 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u7684 ",(0,s.jsx)(l.code,{children:"babel plugins"})," \u5373\u53EF\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"module"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"exports"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"module:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rules:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// handle javascript source loader"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"test:"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"\\."}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"["}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"jt"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"]"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"sx"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"?"}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"$"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"exclude:"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /node_modules/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"use:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"loader:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'babel-loader'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"options:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"plugins:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 3. add mfsu babel plugins"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              ..."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getBabelPlugins"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            ]"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    ]"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"esbuild-handler",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#esbuild-handler",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Esbuild handler"]}),`
`,(0,s.jsxs)(l.p,{children:["\u53E6\u4E00\u79CD\u65B9\u6848\u662F\u4F7F\u7528\u5185\u7F6E\u63D0\u4F9B\u7684 ",(0,s.jsx)(l.code,{children:"esbuild-loader"})," \u6765\u5904\u7406 ",(0,s.jsx)(l.code,{children:"js/ts"})," \u8D44\u6E90\uFF0C",(0,s.jsx)(l.strong,{children:"\u4EC5\u7528\u4E8E\u5F00\u53D1\u73AF\u5883"})," \u3002"]}),`
`,(0,s.jsx)(i.v0,{type:"success",emoji:"\u{1F680}",children:(0,s.jsxs)(l.p,{children:[(0,s.jsx)("strong",{children:"\u4F7F\u7528\u8FD9\u79CD\u65B9\u6848\u7684\u597D\u5904\u662F"}),"\uFF1A\u5728\u5F00\u53D1\u73AF\u5883\u83B7\u5F97\u6BD4 ",(0,s.jsx)(l.code,{children:"babel"})," \u66F4\u5FEB\u7684\u7F16\u8BD1\u548C\u542F\u52A8\u901F\u5EA6"]})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"esbuildLoader"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"require"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'@umijs/mfsu'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"esbuild"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"require"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'esbuild'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"module"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"exports"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"module:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"rules:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"test:"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"\\."}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"["}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"jt"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"]"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"sx"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"?"}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"$"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"exclude:"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /node_modules/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"use:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"loader:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"esbuildLoader"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"options:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"handler:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 3. add mfsu esbuild loader handlers"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"              ..."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getEsbuildLoaderHandler"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            ],"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"target:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'esnext'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"            "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"implementation:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"esbuild"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"          }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    ]"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(i.v0,{type:"warning",emoji:"\u{1F4A1}",children:(0,s.jsxs)(l.p,{children:[(0,s.jsx)("strong",{children:"\u4EC0\u4E48\u65F6\u5019\u6211\u4E0D\u5E94\u8BE5\u4F7F\u7528 esbuild \u65B9\u6848\uFF1F"}),(0,s.jsx)("br",{}),"1. \u6211\u6709\u81EA\u5B9A\u4E49\u7684 ",(0,s.jsx)(l.code,{children:"babel plugins"})," \u5FC5\u987B\u5728\u5F00\u53D1\u73AF\u5883\u4F7F\u7528",(0,s.jsx)("br",{}),"2. \u6211\u9700\u8981\u663E\u793A ",(0,s.jsx)(l.code,{children:"css-in-js"})," \u7684\u5F00\u53D1\u73AF\u5883\u53CB\u597D\u7C7B\u540D\uFF08\u4E00\u822C\u7531 babel plugin \u63D0\u4F9B\u652F\u6301\uFF09",(0,s.jsx)("br",{}),"3. \u5728\u5F00\u53D1\u73AF\u5883\u591A\u9002\u914D\u4E00\u5957 ",(0,s.jsx)(l.code,{children:"esbuild-loader"})," \u7684\u6210\u672C\u5927\u4E8E\u914D\u7F6E ",(0,s.jsx)(l.code,{children:"babel plugins"})," \u7684\u6210\u672C"]})}),`
`,(0,s.jsxs)(l.h3,{id:"4-\u8BBE\u5B9A-webpack-\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#4-\u8BBE\u5B9A-webpack-\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"4. \u8BBE\u5B9A webpack \u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u7B2C\u56DB\u6B65\uFF0C\u8C03\u7528 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u63D0\u4F9B\u7684\u65B9\u6CD5\u6539\u53D8\u4F60\u7684 webpack \u914D\u7F6E\uFF0C\u5728\u8FD9\u91CC\u53EA\u6709\u589E\u91CF\u884C\u4E3A\uFF0C\u4F60\u65E0\u9700\u62C5\u5FC3\u4F1A\u5F71\u54CD\u5230\u4F60\u539F\u6765\u7684\u914D\u7F6E\u5185\u5BB9\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5982\u4E0B\u4EE3\u7801\u6240\u793A\uFF0C",(0,s.jsx)(l.code,{children:"mfsu.setWebpackConfig"})," \u662F\u4E00\u4E2A\u5F02\u6B65\u65B9\u6CD5\uFF0C\u4E3A\u4E86\u8C03\u7528\u4ED6\u4F60\u9700\u8981\u5C06\u539F\u6765\u7684 webpack \u914D\u7F6E\u5355\u72EC\u62BD\u4E3A\u4E00\u4E2A\u5BF9\u8C61 ",(0,s.jsx)(l.code,{children:"config"})," \u4E4B\u540E\uFF0C\u518D\u5C06\u8C03\u7528\u6B64\u65B9\u6CD5\u7684\u8FD4\u56DE\u503C\u5BFC\u51FA\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack.config.js"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"config"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// origin webpack config"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"depConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// webpack config for dependencies"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// [mfsu] 4. inject mfsu webpack config"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"async"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"await"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setWebpackConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"depConfig"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"config"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"module"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"exports"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u5230\u6B64\u4E3A\u6B62\uFF0C",(0,s.jsx)(l.code,{children:"MFSU"})," \u5B8C\u5168\u914D\u7F6E\u5B8C\u6BD5\uFF0C\u4E0B\u9762\u53EF\u4EE5\u5F00\u59CB\u542F\u52A8\u9879\u76EE\u4F7F\u7528\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u4F7F\u7528",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u4F7F\u7528",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u4F7F\u7528"]}),`
`,(0,s.jsxs)(l.p,{children:["\u8FDB\u884C\u5B8C 4 \u6B65\u914D\u7F6E\u540E\uFF0C\u542F\u52A8\u4F60\u7684\u9879\u76EE\uFF0C\u4F60\u53EF\u4EE5\u4ECE\u9879\u76EE\u6839\u76EE\u5F55\u5F97\u5230 ",(0,s.jsx)(l.code,{children:".mfsu"})," \u6587\u4EF6\u5939\uFF0C\u5373 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u7F13\u5B58\u6587\u4EF6\u5939\uFF0C\u8BF7\u5C06\u5176\u6DFB\u52A0\u5230 git \u7684\u5FFD\u7565\u5217\u8868\uFF08\u8FD9\u4E9B\u7F13\u5B58\u6587\u4EF6\u4F60\u4E0D\u5E94\u8BE5\u63D0\u4EA4\u4ED6\u4EEC\uFF09\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"bash","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"bash","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"# .gitignore"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:".mfsu"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u7B26\u5408\u9884\u671F\u65F6\uFF0C\u4F60\u5DF2\u7ECF\u53EF\u4EE5\u4EAB\u53D7 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u5E26\u6765\u7684\u597D\u5904\uFF0C\u5305\u62EC ",(0,s.jsx)(l.code,{children:"esbuild"})," \u5FEB\u901F\u7684\u6253\u5305\u548C\u4E8C\u6B21\u70ED\u542F\u52A8\u7684\u63D0\u901F\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u5176\u4ED6\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5176\u4ED6\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5176\u4ED6\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u4EE5\u4E0B\u662F\u5176\u4ED6\u4F60\u53EF\u80FD\u4F1A\u7528\u5230\u7684 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u5B9E\u4F8B\u914D\u7F6E\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"new"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"MFSU"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"cwd:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"process"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"cwd"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  })"})})]})})}),`
`,(0,s.jsx)(l.p,{children:"\u5176\u4ED6 Options:"}),`
`,(0,s.jsxs)(l.table,{children:[(0,s.jsx)(l.thead,{children:(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.th,{align:"left",children:"option"}),(0,s.jsx)(l.th,{align:"left",children:"default"}),(0,s.jsx)(l.th,{align:"left",children:"description"})]})}),(0,s.jsxs)(l.tbody,{children:[(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"cwd"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"process.cwd()"})}),(0,s.jsx)(l.td,{align:"left",children:"\u9879\u76EE\u6839\u76EE\u5F55"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"getCacheDependency"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"() => {}"})}),(0,s.jsx)(l.td,{align:"left",children:"\u7528\u8FD4\u56DE\u503C\u6765\u5BF9\u6BD4\uFF0C\u4F7F MFSU cache \u65E0\u6548\u7684\u51FD\u6570"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"tmpBase"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"${process.cwd()}/.mfsu"})}),(0,s.jsx)(l.td,{align:"left",children:"MFSU \u7F13\u5B58\u5B58\u653E\u76EE\u5F55"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"unMatchLibs"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"[]"})}),(0,s.jsx)(l.td,{align:"left",children:"\u624B\u52A8\u6392\u9664\u67D0\u4E9B\u4E0D\u9700\u8981\u88AB MFSU \u5904\u7406\u7684\u4F9D\u8D56"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"runtimePublicPath"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"undefined"})}),(0,s.jsxs)(l.td,{align:"left",children:["\u540C umijs > ",(0,s.jsx)(l.a,{href:"https://umijs.org/config#runtimepublicpath",children:(0,s.jsx)(l.code,{children:"runtimePublicPath"})})]})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"implementor"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"undefined"})}),(0,s.jsx)(l.td,{align:"left",children:"webpack \u5B9E\u4F8B\uFF0C\u9700\u8981\u548C\u9879\u76EE\u5185\u4F7F\u7528\u7684\u552F\u4E00\u5B9E\u4F8B\u4E00\u81F4"})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"buildDepWithESBuild"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"false"})}),(0,s.jsxs)(l.td,{align:"left",children:["\u662F\u5426\u4F7F\u7528 ",(0,s.jsx)(l.code,{children:"esbuild"})," \u6253\u5305\u4F9D\u8D56"]})]}),(0,s.jsxs)(l.tr,{children:[(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"onMFSUProgress"})}),(0,s.jsx)(l.td,{align:"left",children:(0,s.jsx)(l.code,{children:"undefined"})}),(0,s.jsx)(l.td,{align:"left",children:"\u83B7\u53D6 MFSU \u7F16\u8BD1\u8FDB\u5EA6\u7684\u56DE\u8C03"})]})]})]}),`
`,(0,s.jsxs)(l.h2,{id:"\u5E38\u89C1\u95EE\u9898",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5E38\u89C1\u95EE\u9898",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5E38\u89C1\u95EE\u9898"]}),`
`,(0,s.jsxs)(l.h4,{id:"\u5982\u4F55\u4FDD\u8BC1\u6211\u7684-mfsu-\u914D\u7F6E\u53EA\u5728\u5F00\u53D1\u73AF\u5883\u751F\u6548",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5982\u4F55\u4FDD\u8BC1\u6211\u7684-mfsu-\u914D\u7F6E\u53EA\u5728\u5F00\u53D1\u73AF\u5883\u751F\u6548",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5982\u4F55\u4FDD\u8BC1\u6211\u7684 MFSU \u914D\u7F6E\u53EA\u5728\u5F00\u53D1\u73AF\u5883\u751F\u6548\uFF1F"]}),`
`,(0,s.jsxs)(l.p,{children:["\u4F7F\u7528\u73AF\u5883\u6807\u8BC6\u907F\u514D\u6240\u6709 ",(0,s.jsx)(l.code,{children:"MFSU"})," \u5728\u751F\u4EA7\u73AF\u5883\u6784\u5EFA\u65F6\u7684\u914D\u7F6E\u4FB5\u5165\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"isDev"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"process"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"env"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"NODE_ENV"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'development'"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isDev"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ? "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"new"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"MFSU"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"implementor:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"webpack"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"buildDepWithESBuild:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }) "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  : "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"undefined"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// e.g."})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"test"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"\\."}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"["}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"jt"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"]"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"sx"}),(0,s.jsx)(l.span,{style:{color:"#D7BA7D"},children:"?"}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"$"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:"/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"exclude"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D16969"},children:" /node_modules/"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"use"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"loader"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'babel-loader'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"options"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#C8C8C8"},children:"plugins"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        ...("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isDev"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? [] : "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"mfsu"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getBabelPlugins"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"())"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      ]"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})})]})}}r.default=t}}]);
