"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[1189],{2470:function(p,r,e){e.r(r);var i=e(279),o=e.n(i),t=e(3236),s=e(2086);function d(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var l;if(window.location.hash.length!==0){var x=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(x.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var h=n.components||{},a=h.wrapper;return a?(0,s.jsx)(a,o()(o()({},n),{},{children:(0,s.jsx)(D,{})})):D();function D(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",div:"div",pre:"pre",code:"code",h3:"h3"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"valtio",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#valtio",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"valtio"]}),`
`,(0,s.jsx)(l.p,{children:"@umijs/max \u5185\u7F6E\u4E86 valtio \u6570\u636E\u6D41\u65B9\u6848\u3002"}),`
`,(0,s.jsxs)(l.h2,{id:"\u542F\u7528-valtio",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u542F\u7528-valtio",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u542F\u7528 valtio"]}),`
`,(0,s.jsx)(l.p,{children:"\u914D\u7F6E\u5F00\u542F\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"valtio:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"\u5F00\u59CB\u4F7F\u7528",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5F00\u59CB\u4F7F\u7528",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u5F00\u59CB\u4F7F\u7528"]}),`
`,(0,s.jsxs)(l.h3,{id:"\u57FA\u672C\u7528\u6CD5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u57FA\u672C\u7528\u6CD5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u57FA\u672C\u7528\u6CD5"]}),`
`,(0,s.jsx)(l.p,{children:"\u6781\u5176\u7B80\u5355\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useSnapshot"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 1\u3001\u5B9A\u4E49\u6570\u636E"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 2\u3001\u4F7F\u7528\u6570\u636E"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"snap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useSnapshot"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"snap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 3\u3001\u66F4\u65B0\u6570\u636E"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"react-\u5916\u8BBF\u95EE",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#react-\u5916\u8BBF\u95EE",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"React \u5916\u8BBF\u95EE"]}),`
`,(0,s.jsx)(l.p,{children:"\u5929\u7136\u652F\u6301\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u6570\u636E\u63A8\u5BFC",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6570\u636E\u63A8\u5BFC",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6570\u636E\u63A8\u5BFC"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxyWithComputed"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxyWithComputed"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}, {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"double"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"snap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"snap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" * "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"2"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"action-\u548C\u5F02\u6B65-action",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#action-\u548C\u5F02\u6B65-action",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Action \u548C\u5F02\u6B65 Action"]}),`
`,(0,s.jsx)(l.p,{children:"\u4E24\u79CD\u7528\u6CD5\uFF0C\u53EF\u4EE5\u548C state \u653E\u4E00\u8D77\uFF0C\u4E5F\u53EF\u4EE5\u5206\u5F00\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u65B9\u6CD5\u4E00\uFF1A\u653E\u4E00\u8D77"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"actions:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"	  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"add"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"	    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u6CE8\u610F\u8FD9\u91CC\u522B\u7528 this.count\uFF0C\u57FA\u4E8E snap \u8C03\u7528\u65F6\u4F1A\u62A5\u9519"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"	    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"	  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u65B9\u6CD5\u4E8C\uFF1A\u5206\u5F00\u653E"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"actions"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"add"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5F02\u6B65 action"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"async"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"addAsync"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"() {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"await"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"fetch"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/api/add'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u6570\u636E\u7ED3\u6784\u7684\u62C6\u5206\u4E0E\u7EC4\u5408",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6570\u636E\u7ED3\u6784\u7684\u62C6\u5206\u4E0E\u7EC4\u5408",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6570\u636E\u7ED3\u6784\u7684\u62C6\u5206\u4E0E\u7EC4\u5408"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u6BD4\u5982\u5982\u4E0B\u5B9A\u4E49"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// state.foo \u548C state.bar \u90FD\u662F proxy\uFF0C\u53EF\u62C6\u5206\u4F7F\u7528"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"foo:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"a:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"bar:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"b:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u7EC4\u5408"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"a:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"bar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"b:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"bar"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u7EC4\u4EF6\u5C01\u88C5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u7EC4\u4EF6\u5C01\u88C5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u7EC4\u4EF6\u5C01\u88C5"]}),`
`,(0,s.jsx)(l.p,{children:"\u5982\u679C props \u5185\u5BB9\u548C state \u65E0\u5173\uFF0C\u53EF\u4EE5\u4E0D\u5904\u7406\uFF1B\u5982\u679C\u6709\u5173\uFF0C\u6309\u4EE5\u4E0B\u65B9\u5F0F\u7528 context \u5305\u4E00\u4E0B\uFF0C\u540C\u65F6\u505A props \u5230 state \u7684\u6570\u636E\u540C\u6B65\u5373\u53EF\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 1\u3001createContext"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"MyContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"createContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 2\u3001Provider"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"value"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useRef"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }))."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"current"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"MyContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Provider"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"value"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"={"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"value"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} />"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// 3\u3001useContext"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"MyContext"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"redux-devtools-\u652F\u6301",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#redux-devtools-\u652F\u6301",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Redux DevTools \u652F\u6301"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"devtools"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"name:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'count'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"enable:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" });"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"redo--undo-\u652F\u6301",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#redo--undo-\u652F\u6301",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Redo & Undo \u652F\u6301"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxyWithHistory"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxyWithHistory"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"value"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"value"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" += "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"undo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"redo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"history"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u6301\u4E45\u5316\u7F13\u5B58",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6301\u4E45\u5316\u7F13\u5B58",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6301\u4E45\u5316\u7F13\u5B58"]}),`
`,(0,s.jsx)(l.p,{children:"\u5F85\u5B9E\u73B0\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxyWithPersistant"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxyWithPersistant"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"count:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"0"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}, {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"type:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'localStorage'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'count'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u6269\u5C55",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6269\u5C55",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6269\u5C55"]}),`
`,(0,s.jsx)(l.p,{children:"valtio \u662F\u57FA\u4E8E\u7EC4\u88C5\u5F0F\u7684\u6269\u5C55\u65B9\u5F0F\uFF0C\u76F8\u6BD4 middleware \u7684\u65B9\u5F0F\u5728\u7C7B\u578B\u63D0\u793A\u4E0A\u4F1A\u66F4\u597D\u4E00\u4E9B\u3002\u6BD4\u5982\u6211\u8981\u5B9E\u73B0\u524D\u9762\u7684 proxyWithPersistant\uFF0C\u7B80\u5355\u70B9\u7684\u65B9\u6848\u53EA\u8981\u8FD9\u6837\uFF0C"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxyWithPersist"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"V"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"val"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"V"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"opts"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {  "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"string"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";  "})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}) {  "})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"local"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"localStorage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"getItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"opts"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");  "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"local"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ? "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"JSON"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"parse"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"local"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") : "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"val"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");  "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"subscribe"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {  "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"localStorage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setItem"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"opts"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"key"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"JSON"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"stringify"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"snapshot"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")));  "})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  });"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";  "})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u517C\u5BB9\u6027",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u517C\u5BB9\u6027",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u517C\u5BB9\u6027"]}),`
`,(0,s.jsx)(l.p,{children:"1\uFF09\u9700\u8981 React 16.8 \u6216\u4EE5\u4E0A\uFF0C2\uFF09\u4E0D\u652F\u6301 IE 11\uFF0C3\uFF09map \u548C set \u4E0D\u80FD\u76F4\u63A5\u7528\uFF0C\u9700\u6539\u7528 valtio \u63D0\u4F9B\u7684 proxyMap \u548C proxySet\u3002"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"proxyMap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"state"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxy"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"todos:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"proxyMap"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"number"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Todo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:">([["}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"id:"}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"1"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"text:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'Learn Umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}]]),"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"filter:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'all'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"});"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u6D4B\u8BD5",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6D4B\u8BD5",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6D4B\u8BD5"]}),`
`,(0,s.jsx)(l.p,{children:"\u53EF\u4EE5\u76F4\u63A5\u6D4B store\uFF0C\u4E5F\u53EF\u4EE5\u6D4B\u57FA\u4E8E store \u7684 React \u7EC4\u4EF6\u3002\u6B63\u5E38\u5199\u7528\u4F8B\u5373\u53EF\uFF0C\u540E\u8005\u63A8\u8350\u7528 @testing-library/react\u3002"})]})}}r.default=d}}]);
