"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[548],{3487:function(j,r,e){e.r(r);var d=e(279),a=e.n(d),D=e(3236),s=e(2086);function h(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,D.useEffect)(function(){var l;if(window.location.hash.length!==0){var x=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(x.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var t=n.components||{},o=t.wrapper;return o?(0,s.jsx)(o,a()(a()({},n),{},{children:(0,s.jsx)(i,{})})):i();function i(){var l=Object.assign({h1:"h1",a:"a",span:"span",h2:"h2",p:"p",code:"code",div:"div",pre:"pre",h3:"h3",h4:"h4",ul:"ul",li:"li"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u6743\u9650",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6743\u9650",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6743\u9650"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u542F\u7528\u65B9\u5F0F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u542F\u7528\u65B9\u5F0F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u542F\u7528\u65B9\u5F0F"]}),`
`,(0,s.jsxs)(l.p,{children:["\u914D\u7F6E\u5F00\u542F\u3002\u540C\u65F6\u9700\u8981 ",(0,s.jsx)(l.code,{children:"src/access.ts"})," \u63D0\u4F9B\u6743\u9650\u914D\u7F6E\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// access \u63D2\u4EF6\u4F9D\u8D56 initial State \u6240\u4EE5\u9700\u8981\u540C\u65F6\u5F00\u542F"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"initialState:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h2,{id:"\u4ECB\u7ECD",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u4ECB\u7ECD",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u4ECB\u7ECD"]}),`
`,(0,s.jsxs)(l.p,{children:["\u6211\u4EEC\u7EA6\u5B9A\u4E86 ",(0,s.jsx)(l.code,{children:"src/access.ts"})," \u4E3A\u6211\u4EEC\u7684\u6743\u9650\u5B9A\u4E49\u6587\u4EF6\uFF0C\u8BE5\u6587\u4EF6\u9700\u8981\u9ED8\u8BA4\u5BFC\u51FA\u4E00\u4E2A\u65B9\u6CD5\uFF0C\u5BFC\u51FA\u7684\u65B9\u6CD5\u4F1A\u5728\u9879\u76EE\u521D\u59CB\u5316\u65F6\u88AB\u6267\u884C\u3002\u8BE5\u65B9\u6CD5\u9700\u8981\u8FD4\u56DE\u4E00\u4E2A\u5BF9\u8C61\uFF0C\u5BF9\u8C61\u7684\u6BCF\u4E00\u4E2A\u503C\u5C31\u5BF9\u5E94\u5B9A\u4E49\u4E86\u4E00\u6761\u6743\u9650\u3002\u5982\u4E0B\u6240\u793A\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// src/access.ts"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"function"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"initialState"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"userId"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"role"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"initialState"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canReadFoo:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canUpdateFoo:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"role"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'admin'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"canDeleteFoo"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"ownerId"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" === "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"userId"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u5176\u4E2D ",(0,s.jsx)(l.code,{children:"initialState"})," \u662F\u901A\u8FC7\u521D\u59CB\u5316\u72B6\u6001\u63D2\u4EF6 ",(0,s.jsx)(l.code,{children:"initial-state"})," \u63D0\u4F9B\u7684\u6570\u636E\uFF0C\u4F60\u53EF\u4EE5\u4F7F\u7528\u8BE5\u6570\u636E\u6765\u521D\u59CB\u5316\u4F60\u7684\u7528\u6237\u6743\u9650\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.h3,{id:"\u6269\u5C55\u7684\u8DEF\u7531\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u6269\u5C55\u7684\u8DEF\u7531\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u6269\u5C55\u7684\u8DEF\u7531\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u914D\u5408 ",(0,s.jsx)(l.a,{href:"./layout-menu",children:"layout"})," \u63D2\u4EF6\u4F60\u53EF\u4EE5\u5F88\u7B80\u5355\u7684\u5B9E\u73B0\u9488\u5BF9\u67D0\u4E9B\u9875\u9762\u7684\u6743\u9650\u63A7\u5236\u3002\u5982\u4E0B\u6240\u793A\uFF0C\u53EA\u6709\u62E5\u6709\u4E86 canReadPageA \uFF08\u5728 ",(0,s.jsx)(l.code,{children:"src/access.ts"})," \u4E2D\u5B9A\u4E49\uFF09\u6743\u9650\uFF0C\u7528\u6237\u624D\u53EF\u4EE5\u8BBF\u95EE\u8BE5\u9875\u9762\u3002\u5426\u5219\u4F1A\u9ED8\u8BA4\u6E32\u67D3 Layout \u63D2\u4EF6\u5185\u7F6E\u7684\u6743\u9650\u9519\u8BEF\u9875\u9762\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"routes"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ["})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/pageA'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'PageA'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'canReadPageA'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u6743\u9650\u5B9A\u4E49\u8FD4\u56DE\u503C\u7684\u67D0\u4E2A key"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"];"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u81EA\u5B9A\u4E49\u6743\u9650\u9875\u9762\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u81EA\u5B9A\u4E49\u6743\u9650\u9875\u9762\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u81EA\u5B9A\u4E49\u6743\u9650\u9875\u9762\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u4E0A\u9762\u8BF4\u5230\u9ED8\u8BA4\u6E32\u67D3 Layout \u63D2\u4EF6\u5185\u7F6E\u7684\u6743\u9650\u9519\u8BEF\u9875\u9762\uFF0C\u5982\u679C\u60F3\u914D\u7F6E\u81EA\u5B9A\u4E49\u6743\u9650\u9875\u9762\u9700\u8981\u5728 ",(0,s.jsx)(l.code,{children:"src/app.tsx"})," \u4E2D\u5B9A\u4E49\u3002"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"tsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"tsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"layout"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"RunTimeLayoutConfig"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u81EA\u5B9A\u4E49 403 \u9875\u9762"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"unAccessible:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"'unAccessible'"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u81EA\u5B9A\u4E49 404 \u9875\u9762"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"noFound:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"'noFound'"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  };"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.h4,{id:"access",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#access",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"access"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"\u5BF9\u5E94\u7684\u6743\u9650\u540D\u79F0\u3002"}),`
`,(0,s.jsxs)(l.h2,{id:"api",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#api",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"API"]}),`
`,(0,s.jsxs)(l.h3,{id:"useaccess",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#useaccess",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"useAccess"]}),`
`,(0,s.jsx)(l.p,{children:"\u6211\u4EEC\u63D0\u4F9B\u4E86\u4E00\u4E2A Hooks \u7528\u4E8E\u5728\u7EC4\u4EF6\u4E2D\u83B7\u53D6\u6743\u9650\u76F8\u5173\u4FE1\u606F\uFF0C\u5982\u4E0B\u6240\u793A\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useAccess"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"PageA"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useAccess"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canReadFoo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5982\u679C\u53EF\u4EE5\u8BFB\u53D6 Foo\uFF0C\u5219..."})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"TODO"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"PageA"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u914D\u5408 ",(0,s.jsx)(l.code,{children:"Access"})," \u7EC4\u4EF6\u53EF\u4EE5\u5F88\u7B80\u5355\u7684\u5B9E\u73B0\u9875\u9762\u5185\u7684\u5143\u7D20\u7684\u6743\u9650\u63A7\u5236\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"access-1",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#access-1",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Access"]}),`
`,(0,s.jsxs)(l.p,{children:["\u53EF\u4EE5\u5728\u4E1A\u52A1\u7EC4\u4EF6\u4E2D\u4F7F\u7528\u63D2\u4EF6\u63D0\u4F9B\u7684 React hook ",(0,s.jsx)(l.code,{children:"useAccess"})," \u4EE5\u53CA\u7EC4\u4EF6 ",(0,s.jsx)(l.code,{children:"<Access />"})," \u5BF9\u5E94\u7528\u8FDB\u884C\u6743\u9650\u63A7\u5236\u4E86\u3002\u7EC4\u4EF6 ",(0,s.jsx)(l.code,{children:"Access"})," \u652F\u6301\u7684\u5C5E\u6027\u5982\u4E0B\uFF1A"]}),`
`,(0,s.jsxs)(l.h4,{id:"accessible",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#accessible",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"accessible"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"boolean"})]}),`
`]}),`
`,(0,s.jsxs)(l.p,{children:["\u662F\u5426\u6709\u6743\u9650\uFF0C\u901A\u5E38\u901A\u8FC7 ",(0,s.jsx)(l.code,{children:"useAcces"})," \u83B7\u53D6\u540E\u4F20\u5165\u8FDB\u6765\u3002"]}),`
`,(0,s.jsxs)(l.h4,{id:"fallback",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#fallback",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"fallback"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"React.ReactNode"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"\u65E0\u6743\u9650\u65F6\u7684\u663E\u793A\uFF0C\u9ED8\u8BA4\u65E0\u6743\u9650\u4E0D\u663E\u793A\u4EFB\u4F55\u5185\u5BB9\u3002"}),`
`,(0,s.jsxs)(l.h3,{id:"children",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#children",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"children"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"React.ReactNode"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"\u6709\u6743\u9650\u65F6\u7684\u663E\u793A\u3002"}),`
`,(0,s.jsx)(l.p,{children:"\u5B8C\u6574\u793A\u4F8B\u5982\u4E0B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"React"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'react'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"useAccess"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"PageA"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useAccess"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"(); "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// access \u7684\u6210\u5458: canReadFoo, canUpdateFoo, canDeleteFoo"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canReadFoo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5982\u679C\u53EF\u4EE5\u8BFB\u53D6 Foo\uFF0C\u5219..."})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"accessible"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canReadFoo"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"fallback"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Can not read foo content."}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        Foo content."})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"accessible"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"canUpdateFoo"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"fallback"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Can not update foo."}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        Update foo."})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"accessible"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"access"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"canDeleteFoo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"foo"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"fallback"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Can not delete foo."}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        Delete foo."})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Access"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  );"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"};"})})]})})}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:[`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"useAccess()"})," \u7684\u8FD4\u56DE\u503C ",(0,s.jsx)(l.code,{children:"access"})," \u5C31\u662F ",(0,s.jsx)(l.code,{children:"src/access.ts"})," \u4E2D\u5B9A\u4E49\u7684\u6743\u9650\u96C6\u5408\uFF0C\u53EF\u4EE5\u5229\u7528\u5B83\u8FDB\u884C\u7EC4\u4EF6\u5185\u4EE3\u7801\u6267\u884C\u6D41\u7684\u63A7\u5236\u3002"]}),`
`]}),`
`,(0,s.jsxs)(l.li,{children:[`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"<Access>"})," \u7EC4\u4EF6\u62E5\u6709 ",(0,s.jsx)(l.code,{children:"accessible"})," \u548C ",(0,s.jsx)(l.code,{children:"fallback"})," \u4E24\u4E2A\u5C5E\u6027\uFF0C\u5F53 ",(0,s.jsx)(l.code,{children:"accessible"})," \u4E3A ",(0,s.jsx)(l.code,{children:"true"})," \u65F6\u4F1A\u6E32\u67D3\u5B50\u7EC4\u4EF6\uFF0C\u5F53 ",(0,s.jsx)(l.code,{children:"accessible"})," \u4E3A ",(0,s.jsx)(l.code,{children:"false"})," \u4F1A\u6E32\u67D3 ",(0,s.jsx)(l.code,{children:"fallback"})," \u5C5E\u6027\u5BF9\u5E94\u7684 ",(0,s.jsx)(l.code,{children:"ReactNode"}),"\u3002"]}),`
`]}),`
`]})]})}}r.default=h}}]);
