"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[949],{6119:function(x,c,n){n.r(c);var i=n(279),r=n.n(i),t=n(3236),s=n(2086);function h(){var l=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var e;if(window.location.hash.length!==0){var p=decodeURIComponent(window.location.hash);setTimeout(function(){var a;(a=document.getElementById(p.slice(1)))===null||a===void 0||a.scrollIntoView()},100)}else window.scrollTo(0,0);(e=document.getElementById("active-nav-item"))===null||e===void 0||e.scrollIntoView({behavior:"smooth",block:"center"})},[]);var D=l.components||{},o=D.wrapper;return o?(0,s.jsx)(o,r()(r()({},l),{},{children:(0,s.jsx)(d,{})})):d();function d(){var e=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",div:"div",pre:"pre",code:"code"},l.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(e.h1,{id:"\u914D\u7F6E\u6587\u4EF6\u683C\u5F0F\u7EA6\u5B9A",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u6587\u4EF6\u683C\u5F0F\u7EA6\u5B9A",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u6587\u4EF6\u683C\u5F0F\u7EA6\u5B9A"]}),`
`,(0,s.jsx)(e.p,{children:"\u4E3A\u4E86\u65B9\u4FBF Umi \u901A\u8FC7 CLI \u6765\u4FEE\u6539\u9879\u76EE\u7684\u914D\u7F6E\uFF0C\u9879\u76EE\u914D\u7F6E\u6587\u4EF6\u9700\u8981\u91C7\u7528\u4E0B\u9762\u4E24\u79CD\u65B9\u5F0F\u6765\u4E66\u5199\u3002"}),`
`,(0,s.jsxs)(e.h2,{id:"\u5BFC\u51FA\u9ED8\u8BA4\u914D\u7F6E\u5BF9\u8C61",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u5BFC\u51FA\u9ED8\u8BA4\u914D\u7F6E\u5BF9\u8C61",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u5BFC\u51FA\u9ED8\u8BA4\u914D\u7F6E\u5BF9\u8C61"]}),`
`,(0,s.jsx)(e.p,{children:"\u63A8\u8350\u8FD9\u6837\u7684\u65B9\u5F0F\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u2705"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {},"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u800C\u4E0D\u662F\u8FD9\u6837\u7684\u65B9\u5F0F\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u274C"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {} }"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"config"})]})]})})}),`
`,(0,s.jsxs)(e.h2,{id:"\u9ED8\u8BA4\u5BFC\u51FA\u914D\u7F6E\u51FD\u6570\u7ED3\u679C",children:[(0,s.jsx)(e.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u9ED8\u8BA4\u5BFC\u51FA\u914D\u7F6E\u51FD\u6570\u7ED3\u679C",children:(0,s.jsx)(e.span,{className:"icon icon-link"})}),"\u9ED8\u8BA4\u5BFC\u51FA\u914D\u7F6E\u51FD\u6570\u7ED3\u679C"]}),`
`,(0,s.jsx)(e.p,{children:"\u63A8\u8350\u8FD9\u6837\u7684\u65B9\u5F0F\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u2705"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {}"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"})"})})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u800C\u4E0D\u662F\u8FD9\u6837\u7684\u65B9\u5F0F\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u274C"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {} }"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:")"})]})]})})}),`
`,(0,s.jsx)(e.p,{children:"\u4E5F\u4E0D\u662F\u8FD9\u6837\u7684\u65B9\u5F0F\uFF1A"}),`
`,(0,s.jsx)(e.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(e.pre,{"data-language":"ts","data-theme":"default",children:(0,s.jsxs)(e.code,{"data-language":"ts","data-theme":"default",children:[(0,s.jsx)(e.span,{className:"line",children:(0,s.jsx)(e.span,{style:{color:"#6A9955"},children:"// \u274C"})}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(e.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#4FC1FF"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(e.span,{style:{color:"#DCDCAA"},children:"defineConfig"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:"({ "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"dva:"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" {}})"})]}),`
`,(0,s.jsxs)(e.span,{className:"line",children:[(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(e.span,{style:{color:"#9CDCFE"},children:"config"}),(0,s.jsx)(e.span,{style:{color:"#D4D4D4"},children:";"})]})]})})})]})}}c.default=h}}]);
