"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[7511],{7520:function(p,r,e){e.r(r);var h=e(279),a=e.n(h),o=e(3519),t=e(3236),s=e(2086);function D(){var n=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,t.useEffect)(function(){var l;if(window.location.hash.length!==0){var j=decodeURIComponent(window.location.hash);setTimeout(function(){var c;(c=document.getElementById(j.slice(1)))===null||c===void 0||c.scrollIntoView()},100)}else window.scrollTo(0,0);(l=document.getElementById("active-nav-item"))===null||l===void 0||l.scrollIntoView({behavior:"smooth",block:"center"})},[]);var x=n.components||{},i=x.wrapper;return i?(0,s.jsx)(i,a()(a()({},n),{},{children:(0,s.jsx)(d,{})})):d();function d(){var l=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",code:"code",div:"div",pre:"pre",h3:"h3",ul:"ul",li:"li",em:"em",strong:"strong"},n.components);return(0,s.jsxs)(s.Fragment,{children:[(0,s.jsxs)(l.h1,{id:"\u8DEF\u7531",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8DEF\u7531"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5728 Umi \u5E94\u7528\u662F",(0,s.jsx)(l.a,{href:"https://en.wikipedia.org/wiki/Single-page_application",children:"\u5355\u9875\u5E94\u7528"}),"\uFF0C\u9875\u9762\u5730\u5740\u7684\u8DF3\u8F6C\u90FD\u662F\u5728\u6D4F\u89C8\u5668\u7AEF\u5B8C\u6210\u7684\uFF0C\u4E0D\u4F1A\u91CD\u65B0\u8BF7\u6C42\u670D\u52A1\u7AEF\u83B7\u53D6 html\uFF0Chtml \u53EA\u5728\u5E94\u7528\u521D\u59CB\u5316\u65F6\u52A0\u8F7D\u4E00\u6B21\u3002\u6240\u6709\u9875\u9762\u7531\u4E0D\u540C\u7684\u7EC4\u4EF6\u6784\u6210\uFF0C\u9875\u9762\u7684\u5207\u6362\u5176\u5B9E\u5C31\u662F\u4E0D\u540C\u7EC4\u4EF6\u7684\u5207\u6362\uFF0C\u4F60\u53EA\u9700\u8981\u5728\u914D\u7F6E\u4E2D\u628A\u4E0D\u540C\u7684\u8DEF\u7531\u8DEF\u5F84\u548C\u5BF9\u5E94\u7684\u7EC4\u4EF6\u5173\u8054\u4E0A\u3002"]}),`
`,(0,s.jsxs)(l.h2,{id:"\u8DEF\u7531\u7C7B\u578B\u914D\u7F6E",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531\u7C7B\u578B\u914D\u7F6E",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8DEF\u7531\u7C7B\u578B\u914D\u7F6E"]}),`
`,(0,s.jsxs)(l.p,{children:["\u8BF7\u53C2\u8003",(0,s.jsx)(l.a,{href:"../api/config#history",children:"\u914D\u7F6E\u6587\u6863"})]}),`
`,(0,s.jsxs)(l.h2,{id:"\u914D\u7F6E\u8DEF\u7531",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E\u8DEF\u7531",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u914D\u7F6E\u8DEF\u7531"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5728\u914D\u7F6E\u6587\u4EF6\u4E2D\u901A\u8FC7 ",(0,s.jsx)(l.code,{children:"routes"})," \u8FDB\u884C\u914D\u7F6E\uFF0C\u683C\u5F0F\u4E3A\u8DEF\u7531\u4FE1\u606F\u7684\u6570\u7EC4\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u6BD4\u5982\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'index'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/user'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'user'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ],"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["Umi 4 \u9ED8\u8BA4\u6839\u636E\u8DEF\u7531\u6765\u8FDB\u884C JavaScript \u6A21\u5757\u6309\u9700\u52A0\u8F7D\u3002\u5982\u679C\u9700\u8981\u5728\u8DEF\u7531\u7EC4\u4EF6\u52A0\u8F7D\u7684\u8FC7\u7A0B\u4E2D\u914D\u7F6E\u81EA\u5B9A\u4E49\u52A0\u8F7D\u7EC4\u4EF6\uFF0C\u5728\u9879\u76EE ",(0,s.jsx)(l.code,{children:"src"})," \u76EE\u5F55\u4E0B\u521B\u5EFA ",(0,s.jsx)(l.code,{children:"loading.tsx"})," \u6216\u8005 ",(0,s.jsx)(l.code,{children:"loading.jsx"})," \u6216\u8005 ",(0,s.jsx)(l.code,{children:"loading.js"})," \u6587\u4EF6\uFF0C\u9ED8\u8BA4\u5BFC\u51FA\u7684\u7EC4\u4EF6\u4F1A\u5728\u7EC4\u4EF6\u52A0\u8F7D\u7684\u65F6\u5019\u6E32\u67D3\u3002"]}),`
`,(0,s.jsx)(o.v0,{emoji:"\u{1F4A1}",children:(0,s.jsx)(l.p,{children:"\u4F60\u53EF\u4EE5\u5728 Chrome \u7684\u8C03\u8BD5\u5DE5\u5177\u7684\u7F51\u7EDC tab \u4E2D\u5C06\u7F51\u7EDC\u8BBE\u7F6E\u6210\u4F4E\u901F\uFF0C\u7136\u540E\u5207\u6362\u8DEF\u7531\u67E5\u770B\u52A8\u6001\u52A0\u8F7D\u4E2D\u7EC4\u4EF6\u7684\u5C55\u793A\u3002"})}),`
`,(0,s.jsxs)(l.h3,{id:"path",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#path",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"path"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"path"})," \u53EA\u652F\u6301\u4E24\u79CD\u5360\u4F4D\u7B26\u914D\u7F6E\uFF0C\u7B2C\u4E00\u79CD\u662F\u52A8\u6001\u53C2\u6570 ",(0,s.jsx)(l.code,{children:":id"})," \u7684\u5F62\u5F0F\uFF0C\u7B2C\u4E8C\u79CD\u662F ",(0,s.jsx)(l.code,{children:"*"})," \u901A\u914D\u7B26\uFF0C\u901A\u914D\u7B26\u53EA\u80FD\u51FA\u73B0\u8DEF\u7531\u5B57\u7B26\u4E32\u7684\u6700\u540E\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u2705 \u4EE5\u4E0B\u662F\u76EE\u524D",(0,s.jsx)(l.em,{children:(0,s.jsx)(l.strong,{children:"\u652F\u6301"})}),"\u7684\u8DEF\u7531\u8DEF\u5F84\u914D\u7F6E\u5F62\u5F0F\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"txt","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"txt","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/groups"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/groups/admin"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/users/:id"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/users/:id/messages"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/files/*"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/files/:id/*"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u274C \u4EE5\u4E0B\u662F\u76EE\u524D",(0,s.jsx)(l.em,{children:(0,s.jsx)(l.strong,{children:"\u4E0D\u652F\u6301"})}),"\u7684\u8DEF\u7531\u8DEF\u5F84\u914D\u7F6E\u5F62\u5F0F\uFF1A"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"txt","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"txt","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/users/:id?"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/tweets/:id(\\d+)"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/files/*/cat.jpg"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"/files-*"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"component",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#component",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"component"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsxs)(l.p,{children:["\u914D\u7F6E location \u548C path \u5339\u914D\u540E\u7528\u4E8E\u6E32\u67D3\u7684 React \u7EC4\u4EF6\u8DEF\u5F84\u3002\u53EF\u4EE5\u662F\u7EDD\u5BF9\u8DEF\u5F84\uFF0C\u4E5F\u53EF\u4EE5\u662F\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u5982\u679C\u662F\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u4F1A\u4ECE ",(0,s.jsx)(l.code,{children:"src/pages"})," \u5F00\u59CB\u627E\u8D77\u3002"]}),`
`,(0,s.jsxs)(l.p,{children:["\u5982\u679C\u6307\u5411 ",(0,s.jsx)(l.code,{children:"src"})," \u76EE\u5F55\u7684\u6587\u4EF6\uFF0C\u53EF\u4EE5\u7528 ",(0,s.jsx)(l.code,{children:"@"}),"\uFF0C\u4E5F\u53EF\u4EE5\u7528 ",(0,s.jsx)(l.code,{children:"../"}),"\u3002\u6BD4\u5982 ",(0,s.jsx)(l.code,{children:"component: '@/layouts/basic'"}),"\uFF0C\u6216\u8005 ",(0,s.jsx)(l.code,{children:"component: '../layouts/basic'"}),"\uFF0C\u63A8\u8350\u7528\u524D\u8005\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"routes",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#routes",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"routes"]}),`
`,(0,s.jsx)(l.p,{children:"\u914D\u7F6E\u5B50\u8DEF\u7531\uFF0C\u901A\u5E38\u5728\u9700\u8981\u4E3A\u591A\u4E2A\u8DEF\u5F84\u589E\u52A0 layout \u7EC4\u4EF6\u65F6\u4F7F\u7528\u3002"}),`
`,(0,s.jsx)(l.p,{children:"\u6BD4\u5982\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/login'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'login'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    {"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'@/layouts/index'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/admin'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'admin'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      ],"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    }, "})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ],"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u7136\u540E\u5728 ",(0,s.jsx)(l.code,{children:"src/layouts/index"})," \u4E2D\u901A\u8FC7 ",(0,s.jsx)(l.code,{children:"<Outlet/>"})," \u6E32\u67D3\u5B50\u8DEF\u7531\uFF0C"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"} "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"style"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"{"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{ "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"padding:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#B5CEA8"},children:"20"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" }"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"}"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u8FD9\u6837\uFF0C\u8BBF\u95EE ",(0,s.jsx)(l.code,{children:"/list"})," \u548C ",(0,s.jsx)(l.code,{children:"/admin"})," \u5C31\u4F1A\u5E26\u4E0A ",(0,s.jsx)(l.code,{children:"src/layouts/index"})," \u8FD9\u4E2A layout \u7EC4\u4EF6\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"redirect",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#redirect",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"redirect"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"\u914D\u7F6E\u8DEF\u7531\u8DF3\u8F6C\u3002"}),`
`,(0,s.jsx)(l.p,{children:"\u6BD4\u5982\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"redirect:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'list'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ],"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u8BBF\u95EE ",(0,s.jsx)(l.code,{children:"/"})," \u4F1A\u8DF3\u8F6C\u5230 ",(0,s.jsx)(l.code,{children:"/list"}),"\uFF0C\u5E76\u7531 ",(0,s.jsx)(l.code,{children:"src/pages/list"})," \u6587\u4EF6\u8FDB\u884C\u6E32\u67D3\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"wrappers",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#wrappers",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"wrappers"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string[]"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:`\u914D\u7F6E\u8DEF\u7531\u7EC4\u4EF6\u7684\u5305\u88C5\u7EC4\u4EF6\uFF0C\u901A\u8FC7\u5305\u88C5\u7EC4\u4EF6\u53EF\u4EE5\u4E3A\u5F53\u524D\u7684\u8DEF\u7531\u7EC4\u4EF6\u7EC4\u5408\u8FDB\u66F4\u591A\u7684\u529F\u80FD\u3002
\u6BD4\u5982\uFF0C\u53EF\u4EE5\u7528\u4E8E\u8DEF\u7531\u7EA7\u522B\u7684\u6743\u9650\u6821\u9A8C\uFF1A`}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"js","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"js","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"routes:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/user'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'user'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"wrappers:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"        "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'@/wrappers/auth'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"      ],"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"path:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/login'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"component:"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'login'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" },"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ]"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u7136\u540E\u5728 ",(0,s.jsx)(l.code,{children:"src/wrappers/auth"})," \u4E2D\uFF0C"]}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"props"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"isLogin"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useAuth"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isLogin"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Outlet"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"else"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/login"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u8FD9\u6837\uFF0C\u8BBF\u95EE ",(0,s.jsx)(l.code,{children:"/user"}),"\uFF0C\u5C31\u901A\u8FC7 ",(0,s.jsx)(l.code,{children:"auth"})," \u7EC4\u4EF6\u505A\u6743\u9650\u6821\u9A8C\uFF0C\u5982\u679C\u901A\u8FC7\uFF0C\u6E32\u67D3 ",(0,s.jsx)(l.code,{children:"src/pages/user"}),"\uFF0C\u5426\u5219\u8DF3\u8F6C\u5230 ",(0,s.jsx)(l.code,{children:"/login"}),"\u3002"]}),`
`,(0,s.jsx)(o.v0,{emoji:"\u{1F6A8}",children:(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"wrappers"})," \u4E2D\u7684\u6BCF\u4E2A\u7EC4\u4EF6\u4F1A\u7ED9\u5F53\u524D\u7684\u8DEF\u7531\u7EC4\u4EF6\u589E\u52A0\u4E00\u5C42\u5D4C\u5957\u8DEF\u7531\uFF0C\u5982\u679C\u4F60\u5E0C\u671B\u8DEF\u7531\u7ED3\u6784\u4E0D\u53D1\u751F\u53D8\u5316\uFF0C\u63A8\u8350\u4F7F\u7528\u9AD8\u9636\u7EC4\u4EF6\u3002\u5148\u5728\u9AD8\u9636\u7EC4\u4EF6\u4E2D\u5B9E\u73B0 wrapper \u4E2D\u7684\u903B\u8F91\uFF0C\u7136\u540E\u4F7F\u7528\u8BE5\u9AD8\u9636\u7EC4\u4EF6\u88C5\u9970\u5BF9\u5E94\u7684\u8DEF\u7531\u7EC4\u4EF6\u3002"]})}),`
`,(0,s.jsx)(l.p,{children:"\u4E3E\u4F8B\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// src/hocs/withAuth.jsx"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"withAuth"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Component"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ()"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"isLogin"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useAuth"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"if"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"isLogin"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:") {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Component"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"else"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"return"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Navigate"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/login"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"/>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// src/pages/user.jsx"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"TheOldPage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = ()"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  ..."})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"withAuth"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"TheOldPage"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"title",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#title",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"title"]}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:["Type: ",(0,s.jsx)(l.code,{children:"string"})]}),`
`]}),`
`,(0,s.jsx)(l.p,{children:"\u914D\u7F6E\u8DEF\u7531\u7684\u6807\u9898\u3002"}),`
`,(0,s.jsxs)(l.h2,{id:"\u9875\u9762\u8DF3\u8F6C",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u9875\u9762\u8DF3\u8F6C",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u9875\u9762\u8DF3\u8F6C"]}),`
`,(0,s.jsxs)(l.p,{children:["\u547D\u4EE4\u5F0F\u8DF3\u8F6C\u8BF7\u4F7F\u7528 ",(0,s.jsx)(l.a,{href:"../api/api#history",children:(0,s.jsx)(l.code,{children:"history"})})," API"]}),`
`,(0,s.jsxs)(l.p,{children:["\u7EC4\u4EF6\u5185\u8FD8\u53EF\u4EE5\u4F7F\u7528 ",(0,s.jsx)(l.a,{href:"../api/api#usenavigate",children:(0,s.jsx)(l.code,{children:"useNavigate"})})," hook"]}),`
`,(0,s.jsxs)(l.h2,{id:"link-\u7EC4\u4EF6",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#link-\u7EC4\u4EF6",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"Link \u7EC4\u4EF6"]}),`
`,(0,s.jsx)(l.p,{children:"\u6BD4\u5982\uFF1A"}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"import"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" { "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" } "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"from"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'umi'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:";"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"export"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#C586C0"},children:"default"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" () "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"=>"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ("})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"<"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"to"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"="}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/users"'}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"Users Page"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#4EC9B0"},children:"Link"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:"</"}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"div"}),(0,s.jsx)(l.span,{style:{color:"#808080"},children:">"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:");"})})]})})}),`
`,(0,s.jsxs)(l.p,{children:["\u7136\u540E\u70B9\u51FB ",(0,s.jsx)(l.code,{children:"Users Page"})," \u5C31\u4F1A\u8DF3\u8F6C\u5230 ",(0,s.jsx)(l.code,{children:"/users"})," \u5730\u5740\u3002"]}),`
`,(0,s.jsx)(l.p,{children:"\u6CE8\u610F\uFF1A"}),`
`,(0,s.jsxs)(l.ul,{children:[`
`,(0,s.jsxs)(l.li,{children:[(0,s.jsx)(l.code,{children:"Link"})," \u53EA\u7528\u4E8E\u5355\u9875\u5E94\u7528\u7684\u5185\u90E8\u8DF3\u8F6C\uFF0C\u5982\u679C\u662F\u5916\u90E8\u5730\u5740\u8DF3\u8F6C\u8BF7\u4F7F\u7528 ",(0,s.jsx)(l.code,{children:"a"})," \u6807\u7B7E"]}),`
`]}),`
`,(0,s.jsxs)(l.h2,{id:"\u8DEF\u7531\u7EC4\u4EF6\u53C2\u6570",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531\u7EC4\u4EF6\u53C2\u6570",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8DEF\u7531\u7EC4\u4EF6\u53C2\u6570"]}),`
`,(0,s.jsxs)(l.p,{children:["Umi4 \u4F7F\u7528 ",(0,s.jsx)(l.a,{href:"https://reactrouter.com/docs/en/v6/api",children:"react-router@6"})," \u4F5C\u4E3A\u8DEF\u7531\u7EC4\u4EF6\uFF0C\u8DEF\u7531\u53C2\u6570\u7684\u83B7\u53D6\u4F7F\u5176 hooks\u3002"]}),`
`,(0,s.jsxs)(l.h3,{id:"match-\u4FE1\u606F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#match-\u4FE1\u606F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"match \u4FE1\u606F"]}),`
`,(0,s.jsx)(l.p,{children:(0,s.jsx)(l.a,{href:"https://reactrouter.com/docs/en/v6/api#usematch",children:"useMatch"})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"match"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useMatch"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'/comp/:id'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// match "})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"params"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"id"'}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"paramId"'})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  },"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"pathname"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/comp/paramId/"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"pathnameBase"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/comp/paramId"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"pattern"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": {"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"path"'}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/comp/:id"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"caseSensitive"'}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"false"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"    "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"end"'}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:":"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"true"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  }"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"location-\u4FE1\u606F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#location-\u4FE1\u606F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"location \u4FE1\u606F"]}),`
`,(0,s.jsx)(l.p,{children:(0,s.jsx)(l.a,{href:"https://reactrouter.com/docs/en/v6/api#uselocation",children:"useLocation"})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"location"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useLocation"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// location"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"pathname"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"/path/"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"search"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'""'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"hash"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'""'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"state"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"null"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"key"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"default"'})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"\u8DEF\u7531\u52A8\u6001\u53C2\u6570",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u8DEF\u7531\u52A8\u6001\u53C2\u6570",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"\u8DEF\u7531\u52A8\u6001\u53C2\u6570"]}),`
`,(0,s.jsx)(l.p,{children:(0,s.jsx)(l.a,{href:"https://reactrouter.com/docs/en/v6/api#useparams",children:"useParams"})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u8DEF\u7531\u914D\u7F6E /comp/:id"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5F53\u524D location /comp/paramId"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"params"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// params"})}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"{"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"  "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"id"'}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:": "}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:'"paramId"'})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}"})})]})})}),`
`,(0,s.jsxs)(l.h3,{id:"query-\u4FE1\u606F",children:[(0,s.jsx)(l.a,{"aria-hidden":"true",tabIndex:"-1",href:"#query-\u4FE1\u606F",children:(0,s.jsx)(l.span,{className:"icon icon-link"})}),"query \u4FE1\u606F"]}),`
`,(0,s.jsx)(l.p,{children:(0,s.jsx)(l.a,{href:"https://reactrouter.com/docs/en/v6/api#usesearchparams",children:"useSearchParams"})}),`
`,(0,s.jsx)(l.div,{"data-rehype-pretty-code-fragment":"",children:(0,s.jsx)(l.pre,{"data-language":"jsx","data-theme":"default",children:(0,s.jsxs)(l.code,{"data-language":"jsx","data-theme":"default",children:[(0,s.jsx)(l.span,{className:"line",children:(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// \u5F53\u524D location /comp?a=b;"})}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#569CD6"},children:"const"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:" ["}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"searchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:", "}),(0,s.jsx)(l.span,{style:{color:"#4FC1FF"},children:"setSearchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"] = "}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"useSearchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"();"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"searchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"get"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"("}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'a'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:")  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// b"})]}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"searchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"."}),(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"toString"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"()  "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// a=b"})]}),`
`,(0,s.jsx)(l.span,{className:"line",children:" "}),`
`,(0,s.jsxs)(l.span,{className:"line",children:[(0,s.jsx)(l.span,{style:{color:"#DCDCAA"},children:"setSearchParams"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"({"}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"a:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'c'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:","}),(0,s.jsx)(l.span,{style:{color:"#9CDCFE"},children:"d:"}),(0,s.jsx)(l.span,{style:{color:"#CE9178"},children:"'e'"}),(0,s.jsx)(l.span,{style:{color:"#D4D4D4"},children:"}) "}),(0,s.jsx)(l.span,{style:{color:"#6A9955"},children:"// location \u53D8\u6210 /comp?a=c&d=e"})]})]})})}),`
`,(0,s.jsxs)(l.p,{children:[(0,s.jsx)(l.code,{children:"searchParams"}),"\u7684 api ",(0,s.jsx)(l.a,{href:"https://developer.mozilla.org/zh-CN/docs/Web/API/URL/searchParams",children:"\u53C2\u8003"})]})]})}}r.default=D}}]);
