"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[1712],{9943:function(D,i,s){s.r(i);var r=s(279),c=s.n(r),o=s(3519),h=s(3236),e=s(2086);function p(){var a=arguments.length>0&&arguments[0]!==void 0?arguments[0]:{};(0,h.useEffect)(function(){var n;if(window.location.hash.length!==0){var j=decodeURIComponent(window.location.hash);setTimeout(function(){var l;(l=document.getElementById(j.slice(1)))===null||l===void 0||l.scrollIntoView()},100)}else window.scrollTo(0,0);(n=document.getElementById("active-nav-item"))===null||n===void 0||n.scrollIntoView({behavior:"smooth",block:"center"})},[]);var m=a.components||{},d=m.wrapper;return d?(0,e.jsx)(d,c()(c()({},a),{},{children:(0,e.jsx)(t,{})})):t();function t(){var n=Object.assign({h1:"h1",a:"a",span:"span",p:"p",h2:"h2",div:"div",pre:"pre",code:"code"},a.components);return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)(n.h1,{id:"tailwind-css-\u63D2\u4EF6",children:[(0,e.jsx)(n.a,{"aria-hidden":"true",tabIndex:"-1",href:"#tailwind-css-\u63D2\u4EF6",children:(0,e.jsx)(n.span,{className:"icon icon-link"})}),"Tailwind CSS \u63D2\u4EF6"]}),`
`,(0,e.jsx)(n.p,{children:"\u5728 Max \u9879\u76EE\u4F7F\u7528 Tailwind CSS \u529F\u80FD\u3002"}),`
`,(0,e.jsxs)(n.h2,{id:"\u914D\u7F6E",children:[(0,e.jsx)(n.a,{"aria-hidden":"true",tabIndex:"-1",href:"#\u914D\u7F6E",children:(0,e.jsx)(n.span,{className:"icon icon-link"})}),"\u914D\u7F6E"]}),`
`,(0,e.jsx)(n.p,{children:"\u4F7F\u7528\u5FAE\u751F\u6210\u5668\u4E00\u952E\u5F00\u542F Tailwind CSS \u63D2\u4EF6"}),`
`,(0,e.jsxs)(o.WD,{children:[(0,e.jsx)(n.p,{children:"Max \u9879\u76EE"}),(0,e.jsx)(n.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(n.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(n.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"npx max g tailwindcss"})}),`
`,(0,e.jsxs)(n.span,{className:"line",children:[(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Update package.json "}),(0,e.jsx)(n.span,{style:{color:"#C586C0"},children:"for"}),(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:" devDependencies"})]}),`
`,(0,e.jsxs)(n.span,{className:"line",children:[(0,e.jsx)(n.span,{style:{color:"#DCDCAA"},children:"set"}),(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:" config:tailwindcss on /project/max-playground/.umirc.ts"})]}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Update .umirc.ts"})}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Write tailwind.config.js"})}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Write tailwind.css"})})]})})}),(0,e.jsx)(n.p,{children:"Umi \u9879\u76EE"}),(0,e.jsx)(n.div,{"data-rehype-pretty-code-fragment":"",children:(0,e.jsx)(n.pre,{"data-language":"bash","data-theme":"default",children:(0,e.jsxs)(n.code,{"data-language":"bash","data-theme":"default",children:[(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"npx umi g tailwindcss"})}),`
`,(0,e.jsxs)(n.span,{className:"line",children:[(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Update package.json "}),(0,e.jsx)(n.span,{style:{color:"#C586C0"},children:"for"}),(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:" devDependencies"})]}),`
`,(0,e.jsxs)(n.span,{className:"line",children:[(0,e.jsx)(n.span,{style:{color:"#DCDCAA"},children:"set"}),(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:" config:tailwindcss on /project/max-playground/.umirc.ts"})]}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Update .umirc.ts"})}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Write tailwind.config.js"})}),`
`,(0,e.jsx)(n.span,{className:"line",children:(0,e.jsx)(n.span,{style:{color:"#D4D4D4"},children:"info  - Write tailwind.css"})})]})})})]}),`
`,(0,e.jsxs)(n.p,{children:["\u81F3\u6B64\u5C31\u53EF\u4EE5\u5728\u9879\u76EE\u4E2D\u4F7F\u7528 Tailwind CSS \u7684\u6837\u5F0F\uFF1B\u9879\u76EE\u6839\u76EE\u5F55\u7684 ",(0,e.jsx)(n.code,{children:"tailwind.config.js"})," \u548C ",(0,e.jsx)(n.code,{children:"tailwind.css"})," \u6839\u636E\u9700\u8981\u4FEE\u6539\u914D\u7F6E\u3002"]})]})}}i.default=p}}]);
